### ISSUE TITLE
Adapt  existing sources to new IntelliJ Plugin template

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-intellij-plugin#1]
The current sourcecode comes without a build tool and without any information how the "generated" code in there was generated.
I want to adopt the code to a modern IntelliJ plugin structure (based on this official template: https://github.com/JetBrains/intellij-platform-plugin-template) and configure a proper build process for it.

**Comment by a4z** [comment]
Great job! as you said, we will first split in repos and have to check then that everything works 

a plugin like this is maybe very hard to unit test and automate the and we will need the help from users for feedback, but this is an awesome start.
