### ISSUE TITLE
clarify general licensing conditions

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-intellij-plugin#15]
The code is currently licensed with Apache 2.0 and a Copyright to Dropbox.

The cross-language-cpp organization does not intend to just fork the original software from dropbox, but rather gain ownership of it as dropbox has stopped maintaining it.

Yet still all files have a Copyright notice that claims Dropbox as the owner.

The Apache License states:
> In every licensed file, original copyright, patent, trademark, and attribution notices must be preserved (excluding notices that do not pertain to any part of the derivative works). In every licensed file changed, a notification must be added stating that changes have been made to that file.

As a project maintainer I want to clarify if this applies to the code that was derived from the original dropbox repository and is now maintained under the cross-langugage-cpp organization.

Personally I would prefer to re-license all files to the cross-language-cpp organization, if this is a legal option.

This question also applies to the [djinni-generator](https://github.com/cross-language-cpp/djinni-generator) & [djinni-support-lib](https://github.com/cross-language-cpp/djinni-support-lib) repos.

**Comment by jothepro** [comment]
Just a random idea: Maybe its a good way to add 2 copyright claims?
```
Copyright 2014 Dropbox, Inc.
Copyright 2020 cross-langugage-cpp
```

**Comment by a4z** [comment]
exactly, this is what I meant with my comment 
just drop a 2020 notice for you, or the project

**Comment by jothepro** [comment]
oh ah that one was easy :D
