### ISSUE TITLE
Plugin doesn't handle methods with const prefix

### ISSUE THREAD

**Issue by sasq64** [cross-language-cpp/djinni-intellij-plugin#17]
![djinni_error](https://user-images.githubusercontent.com/531713/99361046-c8e97e80-28b1-11eb-8437-9b948b05da4f.png)

Any method prefixed with const gets an error at the first parentheses.

**Comment by a4z** [comment]
just a guess 

https://github.com/cross-language-cpp/djinni-intellij-plugin/blob/6f9533289686dfc0ad91cd0d33c1a778efaf7d34/src/main/java/com/github/cross_language_cpp/djinni_intellij_plugin/Djinni.bnf#L132

->

`interfaceMemberFunction ::= [static] [const] identifier LEFT_PARAM_BRACE interfaceFunctionParamList? RIGHT_PARAM_BRACE [COLON typeReference] SEMICOLON`


@jothepro , do you have time / possibility to check that?

**Comment by jothepro** [comment]
Fixed in [v0.10.2](https://github.com/cross-language-cpp/djinni-intellij-plugin/releases/tag/v0.10.2)
The update should soon be available in the jetbrains marketplace.
