### ISSUE TITLE
remove upper limit for IDE comptibility?

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-intellij-plugin#27]
Some time ago the IntelliJ platform got a major update to 2020.3

The plugin refused to work on this new version because the `until-build` property was set to `202.*`.

As a maintainer I'd like to get rid of this "upper version limit", as it will repeatedly make our plugin uncompatible with newer versions of IntelliJ, while it may still be working.

**Comment by jothepro** [comment]
First research: The upper version  limit (`untilBuild`) is being set in the `plugin.xml` by the `patchPluginXml` gradle task.
[I cannot find documentation wether this pugin-property is mandatory](https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_configuration_file.html).

Just not setting a `untilBuild` in `patchPluginXml` doesn't work, it make `untilBuild` fallback to the value of `sinceBuild`:
```
patchPluginXml {
        version(version)
        sinceBuild("193")
    }
```
leads to
```
<idea-version since-build="193" until-build="193.*"/>
```

Maybe not setting a `sinceBuild` as well may be the solution?

**Comment by a4z** [comment]
yes, I think, because the old plugin is always there. it never disappears when a new version arrives. 
so we can have a look there
and I also ask on a place where some JEtBrains folk is around , maybe they know 
https://cpplang.slack.com/archives/C44FNR9PS/p1608796707104200
