### ISSUE TITLE
deploy plugin from new repo

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-intellij-plugin#3]

**Comment by a4z** [comment]
I wonder if we could make this
https://github.com/cross-language-cpp/djinni-intellij-plugin/blob/5dfe39039a81f2d8639679bf1f436838a212ada8/.github/workflows/release.yml#L63
a bit more selective, just for the case something goes wrong, to push only the change-log and not everything changed in the repo? 

also, how to we solve the problem to allow gh-actions to push to the repo, can there be make a special rule for that account?

**Comment by jothepro** [comment]
deploying the plugin via github actions [was successful](https://plugins.jetbrains.com/plugin/15307-djinni-idl-file-support/versions/stable/101114), so I will close this issue.
I created #7 for talking about the questionable Changelog patching during the release process.
