### ISSUE TITLE
fix pipeline to work with protected main branch

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-intellij-plugin#7]
The `main` branch of this repository is protected & merging into it requires at least 1 approval from another user. This seems to collide with the release process of the intellij plugin used as a template for this repo: On release it tries to modify the CHANGELOG.md file in `main`. 

We need to figure out a way around this.
- ~~Is it possible to give the github action special rights, so it can also manipulate `main`?~~
- ...?

Example on what goes wrong: https://github.com/cross-language-cpp/djinni-intellij-plugin/runs/1339227838?check_suite_focus=true

**Comment by jothepro** [comment]
as @a4z noted in #6, it seems to not be possible to give actions special rights on the `main` branch:

> I checked the settings, and this seems not to be possible. To give special permissions to the githube action account.
> 
> But I do not think that this is a problem, since I am unsure if a auto commit to master is a good idea anyway.
> I think the change-log would not be part of the release tag version, so it would come to late to the party .....
> 
> IF we want something like that , we might have to start thinking about at multi stage release branch
> 
> PR-> staging, if staging good change log and auto commit fo it -> pr to main -> deploy

I agree that it might be worth thinking about a different approach, as the whole "patching the Changelog  and pushing it AFTER the tag has been set"-thing seems questionable.

**Comment by a4z** [comment]
I suggest to close that issue, and continue with #25  , investigate in possibilities, that might include a change of the current action workflow

**Comment by jothepro** [comment]
I agree 👍
