### ISSUE TITLE
Improve plugin description for plugin approval

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-intellij-plugin#9]
During approval process, I got this e-mail:

> Hello,
> 
> Thank you for submitting your plugin.
> 
> Please provide a more detailed plugin description and usage instructions. You can update it in the plugin.xml file and upload it to the Marketplace again.
> 
> We are looking forward to approving your plugin.

**Comment by a4z** [comment]
do you know what to do? 
there is no plugin.xml so far, I think....

**Comment by jothepro** [comment]
Yep, I know what to do. The plugin.xml is hidden deep inside the project: https://github.com/cross-language-cpp/djinni-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml

The plugin description is pulled from the README.md: Everything between these comments will appear as plugin description:
```
<!-- Plugin description -->
<!-- Plugin description end -->
```

**Comment by jothepro** [comment]
I'm not sure how to format the usage instructions inside the plugin.xml though. But I don't think this will be a problem.
